%YAML:1.0 # need to specify the file type at the top!

verbosity: "INFO"

use_fej: true
integration: "rk4"
use_stereo: false
max_cameras: 1

use_imuavg: true
use_rk4int: true

calib_cam_extrinsics: true
calib_cam_intrinsics: true
calib_cam_timeoffset: true
calib_imu_intrinsics: false
calib_imu_g_sensitivity: false

max_clones: 11
max_slam: 50
max_slam_in_update: 25
max_msckf_in_update: 40
dt_slam_delay: 0.0

gravity_mag: 9.80

feat_rep_msckf: "GLOBAL_3D"
feat_rep_slam: "GLOBAL_3D"
feat_rep_aruco:"GLOBAL_3D"

try_zupt: false
zupt_chi2_multipler: 0
zupt_max_velocity: 0.1
zupt_noise_multiplier: 50
zupt_max_disparity: 1.5
zupt_only_at_beginning: false

# ==================================================================

init_window_time: 2.0
init_imu_thresh: 0.30
init_max_disparity: 2.0
init_max_features: 200

init_dyn_use: false
init_dyn_mle_opt_calib: false
init_dyn_mle_max_iter: 50
init_dyn_mle_max_time: 0.05
init_dyn_mle_max_threads: 6
init_dyn_num_pose: 6
init_dyn_min_deg: 20.0

init_dyn_inflation_ori: 10
init_dyn_inflation_vel: 100
init_dyn_inflation_bg: 10
init_dyn_inflation_ba: 100
init_dyn_min_rec_cond: 1e-20

init_dyn_bias_g: [0.0, 0.0, 0.0]
init_dyn_bias_a: [0.0, 0.0, 0.0]
# ==================================================================

record_timing_information: false
record_timing_filepath: "/tmp/traj_timing.txt"

save_total_state: false
filepath_est: "/tmp/ov_estimate.txt"
filepath_std: "/tmp/ov_estimate_std.txt"
filepath_gt: "/tmp/ov_groundtruth.txt"

# ==================================================================

use_klt: true
num_pts: 200
fast_threshold: 50
grid_x: 5
grid_y: 5
min_px_dist: 15
ransac_th: 2.0
knn_ratio: 0.70
track_frequency: 30.0
downsample_cameras: false
num_opencv_threads: 4
histogram_method: "HISTOGRAM"

fi_refine_features: true

use_aruco: false
num_aruco: 1024
downsize_aruco: true

# ==================================================================

up_msckf_sigma_px: 1.5
up_msckf_chi2_multipler: 0.8
up_slam_sigma_px: 1.5
init_slam_chi2_multipler: 0.8
up_slam_chi2_multipler: 1
up_aruco_sigma_px: 1
up_aruco_chi2_multipler: 1

use_mask: false

relative_config_imu: "kalibr_imu_chain.yaml"
relative_config_imucam: "kalibr_imucam_chain.yaml"